version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: prisma_user # Usuário que o Prisma vai usar
      POSTGRES_PASSWORD: password123 # Senha de desenvolvimento (SIMPLES!)
      POSTGRES_DB: squadra_db # Nome do banco de dados
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
